
-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 14:37:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bibliotheque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotheque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotheque` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema universite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universite` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bibliotheque` ;

-- -----------------------------------------------------
-- Table `bibliotheque`.`exemplaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`exemplaire` (
  `code_rayon` INT NOT NULL,
  `titre` VARCHAR(25) NOT NULL,
  `code_editeur` INT NOT NULL,
  `code_usure` INT NOT NULL,
  `date_achat` DATE NOT NULL,
  `demande_abonne` VARCHAR(45) NOT NULL,
  `disponibilite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code_rayon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotheque`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`date` (
  `date_id` INT NOT NULL,
  `date_pret` DATE NOT NULL,
  `date_retour` DATE NOT NULL,
  `exemplaire_code_rayon` INT NOT NULL,
  PRIMARY KEY (`date_id`),
  CONSTRAINT `fk_date_exemplaire1`
    FOREIGN KEY (`exemplaire_code_rayon`)
    REFERENCES `bibliotheque`.`exemplaire` (`code_rayon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_date_exemplaire1_idx` ON `bibliotheque`.`date` (`exemplaire_code_rayon` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bibliotheque`.`abonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`abonne` (
  `matricule` INT NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(40) NOT NULL,
  `telephone` INT NOT NULL,
  `date_de_naissance` DATE NOT NULL,
  `categorie_age` CHAR(8) NOT NULL,
  `categorie_pro` VARCHAR(45) NOT NULL,
  `date_date_id` INT NOT NULL,
  PRIMARY KEY (`matricule`),
  CONSTRAINT `fk_abonne_date1`
    FOREIGN KEY (`date_date_id`)
    REFERENCES `bibliotheque`.`date` (`date_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_abonne_date1_idx` ON `bibliotheque`.`abonne` (`date_date_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bibliotheque`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`auteur` (
  `id_auteur` INT NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_auteur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotheque`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`genre` (
  `id_genre` INT NOT NULL,
  `genre_` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotheque`.`editeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`editeur` (
  `id_editeur` INT NOT NULL,
  `nom_editeur` VARCHAR(15) NOT NULL,
  `année_edition` YEAR NOT NULL,
  `genre_id_genre` INT NOT NULL,
  PRIMARY KEY (`id_editeur`, `genre_id_genre`),
  CONSTRAINT `fk_editeur_genre1`
    FOREIGN KEY (`genre_id_genre`)
    REFERENCES `bibliotheque`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_editeur_genre1_idx` ON `bibliotheque`.`editeur` (`genre_id_genre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bibliotheque`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`livre` (
  `id_livre` INT NOT NULL,
  `titre` VARCHAR(50) NOT NULL,
  `Code_achat_catalogue` INT NOT NULL,
  `exemplaire_code_rayon` INT NOT NULL,
  `genre_id_genre` INT NOT NULL,
  `date_date_id` INT NOT NULL,
  PRIMARY KEY (`id_livre`, `genre_id_genre`),
  CONSTRAINT `fk_livre_exemplaire1`
    FOREIGN KEY (`exemplaire_code_rayon`)
    REFERENCES `bibliotheque`.`exemplaire` (`code_rayon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_genre1`
    FOREIGN KEY (`genre_id_genre`)
    REFERENCES `bibliotheque`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_date1`
    FOREIGN KEY (`date_date_id`)
    REFERENCES `bibliotheque`.`date` (`date_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_livre_exemplaire1_idx` ON `bibliotheque`.`livre` (`exemplaire_code_rayon` ASC) VISIBLE;

CREATE INDEX `fk_livre_genre1_idx` ON `bibliotheque`.`livre` (`genre_id_genre` ASC) VISIBLE;

CREATE INDEX `fk_livre_date1_idx` ON `bibliotheque`.`livre` (`date_date_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bibliotheque`.`motcle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`motcle` (
  `idmot_cle` VARCHAR(50) NULL DEFAULT NULL,
  `livre_id_livre` INT NOT NULL,
  `livre_genre_id_genre` INT NOT NULL,
  PRIMARY KEY (`livre_id_livre`, `livre_genre_id_genre`),
  CONSTRAINT `fk_motcle_livre1`
    FOREIGN KEY (`livre_id_livre` , `livre_genre_id_genre`)
    REFERENCES `bibliotheque`.`livre` (`id_livre` , `genre_id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliotheque`.`abonne_has_livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`abonne_has_livre` (
  `abonne_matricule` INT NOT NULL,
  `livre_id_livre` INT NOT NULL,
  PRIMARY KEY (`abonne_matricule`, `livre_id_livre`),
  CONSTRAINT `fk_abonne_has_livre_abonne`
    FOREIGN KEY (`abonne_matricule`)
    REFERENCES `bibliotheque`.`abonne` (`matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_abonne_has_livre_livre1`
    FOREIGN KEY (`livre_id_livre`)
    REFERENCES `bibliotheque`.`livre` (`id_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_abonne_has_livre_livre1_idx` ON `bibliotheque`.`abonne_has_livre` (`livre_id_livre` ASC) VISIBLE;

CREATE INDEX `fk_abonne_has_livre_abonne_idx` ON `bibliotheque`.`abonne_has_livre` (`abonne_matricule` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bibliotheque`.`livre_has_auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque`.`livre_has_auteur` (
  `livre_id_livre` INT NOT NULL,
  `auteur_id_auteur` INT NOT NULL,
  PRIMARY KEY (`livre_id_livre`, `auteur_id_auteur`),
  CONSTRAINT `fk_livre_has_auteur_livre1`
    FOREIGN KEY (`livre_id_livre`)
    REFERENCES `bibliotheque`.`livre` (`id_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_auteur_auteur1`
    FOREIGN KEY (`auteur_id_auteur`)
    REFERENCES `bibliotheque`.`auteur` (`id_auteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_livre_has_auteur_auteur1_idx` ON `bibliotheque`.`livre_has_auteur` (`auteur_id_auteur` ASC) VISIBLE;

CREATE INDEX `fk_livre_has_auteur_livre1_idx` ON `bibliotheque`.`livre_has_auteur` (`livre_id_livre` ASC) VISIBLE;

USE `universite` ;

-- -----------------------------------------------------
-- Table `universite`.`annee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universite`.`annee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `annee_` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `universite`.`enseignants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universite`.`enseignants` (
  `matricule` INT NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`matricule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `universite`.`etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universite`.`etudiants` (
  `matricule` INT NOT NULL,
  PRIMARY KEY (`matricule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `universite`.`salles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universite`.`salles` (
  `numero` INT NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `universite`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universite`.`modules` (
  `code` CHAR(5) NOT NULL,
  `intitule` VARCHAR(20) NOT NULL,
  `niveau` CHAR(2) NOT NULL,
  `suit` VARCHAR(5) NOT NULL,
  `resp` INT NOT NULL,
  `numero` INT NULL DEFAULT NULL,
  `matricule` INT NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  CONSTRAINT `matricule`
    FOREIGN KEY (`matricule`)
    REFERENCES `universite`.`enseignants` (`matricule`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `universite`.`salles` (`numero`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `numero_idx` ON `universite`.`modules` (`numero` ASC) VISIBLE;

CREATE INDEX `matricule_idx` ON `universite`.`modules` (`matricule` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `universite`.`inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universite`.`inscription` (
  `etud` INT NOT NULL,
  `module` CHAR(5) NULL DEFAULT NULL,
  `anneeU` INT NULL DEFAULT NULL,
  `code` CHAR(5) NULL DEFAULT NULL,
  `annee_` INT NULL DEFAULT NULL,
  PRIMARY KEY (`etud`),
  CONSTRAINT `annee_`
    FOREIGN KEY (`annee_`)
    REFERENCES `universite`.`annee` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `code`
    FOREIGN KEY (`code`)
    REFERENCES `universite`.`modules` (`code`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `code_idx` ON `universite`.`inscription` (`code` ASC) VISIBLE;

CREATE INDEX `annee__idx` ON `universite`.`inscription` (`annee_` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;